import React from "react";

const Imgy = [
  "doremon.jpg",
  "LordKrishna.jpg",
  "LordHanuman.jpg",
  "BabyCow.jpg",
  "CuteBtsArmy.jpg",
  "rose.jpg",
  "RoseColor.jpg",
  "FlowerGarden.jpg",
  "BeautifulSketch.jpg",
  "Bird.jpg",
  "NoonSwing.jpg",
  "Pony.jpg",
  "Diwali.jpg",
  "Girl_swinging.jpg",
  "Pencil SketchGirl.jpg",
  "oggy.jpg",
  "Flowerpot.jpg",
  "ColorArt.jpg",
  "Fishes.jpg",
  "DidiSketch.jpg",
  "Princess.jpg",
  "Art.jpg",
  "NightArt.jpg",
  "Butterfly.jpg",
  "BlackPink.jpg",
  "ArtFlower.jpg",
  "WinterGirl.jpg",
  "SceneryBeautiful.jpg",
  "MarineAnimal.jpg",
  "NightScene.jpg",
  "SeashoreScene.jpg",
  "Deer.jpg",
  "Mushroom.jpg",
  "Scenery.jpg",
  "Flowers.jpg",
  "Cat.jpg",
  "KimJoeHung.jpg",
  "Collage.jpg",
  "Duck.jpg",
  "PrincessBack.jpg",
  "TriColor.jpg",
  "PeacockArt.jpg",
  "BTS.jpg",
  "HipHopGirl.jpg",
  "CuteGirl.jpg",
  "SketchHouse.jpg",
  "HouseArt.jpg",
  "BtsArmy.jpg",
  "PrincessBarbie.jpg",
  "PotSketch.jpg",
  "RosePencil.jpg",
  "Peacock.jpg",
  "Unicorn.jpg",
  "Tree.jpg",
  "GirlSketch.jpg",
  "Devil.jpg",
  "CuteGanesha.jpg",
  "RareArt.jpg",
  "NoonScenery.jpg",
  "LordGanesha.jpg",
  "Monkey.jpg",
  "BellyDance.jpg",
  "Autumn Tree.jpg",
  "BtsSign.jpg",
  "ColorTree.jpg",
  "TinyTan.jpg",
  "PrincessDoll.jpg",
  "PenSketchHouse.jpg",
  "UnicornPony.jpg",
];

export default Imgy;
